### ISSUE TITLE
Incorrect selection of rangeXX functions in Randomizer

### ISSUE THREAD

**Issue by TimWolla** [arokettu/php-random-polyfill#1]
https://github.com/arokettu/php-random-polyfill/blob/bfe5d12743f5283e62a21d3ae335f434753db17a/src/Randomizer.php#L136-L138

You've inverted the logic for the `umax` check. If `umax > UINT32_MAX` then the 64 bit variant must be used.

**Comment by arokettu** [comment]
Oops. Thanks!

**Comment by arokettu** [comment]
@TimWolla Since you're here I would be grateful if you answer a couple of my questions

1. Your personal opinion whether this lib should include the other 2 algorithms
2. Do you think pickArrayKeys() in userland can be reliable? I have a poor understanding of what it does with hash tables

**Comment by TimWolla** [comment]
> Your personal opinion whether this lib should include the other 2 algorithms

Yes. The Mt19937 engine should be considered a compatibility-only engine and my hope is to document it as such. Both the Xoshiro and the PCG are better in about every metric possible.

> Do you think pickArrayKeys() in userland can be reliable? I have a poor understanding of what it does with hash tables

I don't think so and your question made me realize that the external behavior of it is pretty intransparent, as it relies on the internal HT structure: See php/doc-en#1731.

**Comment by arokettu** [comment]
Fixed: https://github.com/arokettu/php-random-polyfill/commit/8c93011b569a9fc93f28a9596bfc87895925a4fb
