### ISSUE TITLE
Chained exceptions not implemented

### ISSUE THREAD

**Issue by TimWolla** [arokettu/php-random-polyfill#2]
One thing you might not be aware of: Whenever the C code throws an Exception, while an Exception is already thrown, the latter will automatically be set as the `previous` of the former.

https://github.com/arokettu/php-random-polyfill/blob/be686fb41be78670658d7fb0a15cf9a273c4cede/src/Engine/PcgOneseq128XslRr64.php#L77

will need to look like `throw new RuntimeException('Failed to generate a random seed', 0, $e);`. The same might or might not apply in the other locations.

**Comment by arokettu** [comment]
Thanks, I wasn't aware. I never worked with PHP's C code before, only with Ruby's a bit

**Comment by arokettu** [comment]
Fixed
